// <auto-generated />
using System;
using Fortinite_Project.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fortinite_Project.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("CosmeticoItemAdquirido", b =>
                {
                    b.Property<string>("CosmeticoId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemAdquiridoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CosmeticoId", "ItemAdquiridoId");

                    b.HasIndex("ItemAdquiridoId");

                    b.ToTable("CosmeticoItemAdquirido");
                });

            modelBuilder.Entity("Fortinite_Project.Web.Models.Cosmetico", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Preco")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Raridade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("bundleItemsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("coresJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("dataInclusao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isBundle")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isForSale")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Cosmeticos");
                });

            modelBuilder.Entity("Fortinite_Project.Web.Models.HistoricoTransacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CosmeticoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataTransacao")
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoTransacao")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Valor")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CosmeticoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistoricoTransacoes");
                });

            modelBuilder.Entity("Fortinite_Project.Web.Models.ItemAdquirido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ItensAdquiridos");
                });

            modelBuilder.Entity("Fortinite_Project.Web.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("creditos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CosmeticoItemAdquirido", b =>
                {
                    b.HasOne("Fortinite_Project.Web.Models.Cosmetico", null)
                        .WithMany()
                        .HasForeignKey("CosmeticoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fortinite_Project.Web.Models.ItemAdquirido", null)
                        .WithMany()
                        .HasForeignKey("ItemAdquiridoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fortinite_Project.Web.Models.HistoricoTransacao", b =>
                {
                    b.HasOne("Fortinite_Project.Web.Models.Cosmetico", "Cosmetico")
                        .WithMany("HistoricoTransacao")
                        .HasForeignKey("CosmeticoId");

                    b.HasOne("Fortinite_Project.Web.Models.Usuario", "Usuario")
                        .WithMany("HistoricoTransacao")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Cosmetico");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fortinite_Project.Web.Models.ItemAdquirido", b =>
                {
                    b.HasOne("Fortinite_Project.Web.Models.Usuario", "Usuario")
                        .WithMany("ItemAdquirido")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Fortinite_Project.Web.Models.Cosmetico", b =>
                {
                    b.Navigation("HistoricoTransacao");
                });

            modelBuilder.Entity("Fortinite_Project.Web.Models.Usuario", b =>
                {
                    b.Navigation("HistoricoTransacao");

                    b.Navigation("ItemAdquirido");
                });
#pragma warning restore 612, 618
        }
    }
}
